name: Meu primeiro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  GrupoTeste:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name:  Primeiro comando
        run: echo Executando o que solicitei

      - name: Segundo comando
        run: |
          echo Segundo comando em execução
          echo Projeto Teste
